name: algs4
description: A sample command-line application.
version: 0.0.1
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0-0 <3.0.0'

#dependencies:
#  path: ^1.7.0

dev_dependencies:
  pedantic: ^1.9.2
  effective_dart: ^1.3.0
  test: ^1.15.7
  vm_service: ^5.5.0